### ISSUE TITLE
User Home Page refactor/UI tweaks

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#361] opened 2018-12-10 19:16 UTC
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evansiroky](https://github.com/evansiroky)**
_Saturday Oct 20, 2018 at 00:18 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/252_

----

Bumping https://github.com/conveyal/datatools-ui/issues/15 into here.  Just had to fix a bug where the page wasn't loading due to an issue with the RegionSearch component which essential does nothing.

**Comment by evansiroky** [comment] 2019-02-08 05:32
Closing, as this is a duplicate of #15.

**Closed by evansiroky** 2019-02-08 05:32 UTC
Labels: imported
